### ISSUE TITLE
[0.9.1] test failure with library 0.7.1

### ISSUE THREAD

**Issue by remicollet** [jbboehr/php-handlebars#70]
With library 0.7.0, everything is ok

With library 0.7.1

```
TEST 1256/1258 [tests/vm/renderFromBinaryString.phpt]
========DIFF========
002+ bool(false)
002- bool(true)
========DONE========
FAIL Handlebars\VM::renderFromBinaryString() [tests/vm/renderFromBinaryString.phpt] 
```

**Comment by jbboehr** [comment]
Hm, having trouble replicating this one. It could happen if the extension v0.9.1 is compiled against handlebars v0.7.0 but run against handlebars v0.7.1. Could that be the issue?

I will patch the test to not fail in this case.

**Comment by remicollet** [comment]
> Hm, having trouble replicating this one. It could happen if the extension v0.9.1 is compiled against handlebars v0.7.0 but run against handlebars v0.7.1. Could that be the issue?

Strange...
It fails with 0.7.1, build and runtime.

**Comment by jbboehr** [comment]
@remicollet Ok, I'm adding a fedora build via docker in travis and have released handlebars.c [v0.7.2](https://github.com/jbboehr/handlebars.c/compare/v0.7.1...v0.7.2) which should fix it, no update for the extension should be necessary.

There is no practical issue with any version, it's simply a test to check if the serialized opcodes are deterministic. There was a field used only during serialization that wasn't getting patched to a relative pointer.

Now I get to find out why it *didn't* fail on my other builds :sweat_smile:

**Comment by remicollet** [comment]
I confirm, build is OK using library 0.7.2 and test suite passes

**Comment by jbboehr** [comment]
Sweet, thanks!
